version: '3.5'

services:
  nest:
    container_name: nest
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 5001:5001
    networks:
      - add_net
    depends_on:
      - postgres
    volumes:
      - ./:/app/
    restart: always
  postgres:
    container_name: postgres
    image: postgres:9.6.23
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - add_net
    restart: always
    # volumes:
    #   - ./db_data:/var/lib/postgresql/data
networks:
  add_net:
    driver: bridge
