version: '3.5'

services:
  add-be:
    container_name: add-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      # 이미 5000 포트를 사용하고 있는 경우 콜론 앞 포트 번호 변경
      - 5000:5000
    networks:
      - add-network
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - ./.env
    ports:
      # 이미 15432 포트를 사용하고 있는 경우 콜론 앞 포트 번호 변경
      - 15432:5432
    networks:
      - add-network
    restart: always
    # 컨테이너 종료 시에도 데이터를 유지하고 싶은 경우 아래 주석 해제
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data
networks:
  add-network:
    driver: bridge
