version: '3.5'

services:
  add-be:
    container_name: add-be
    image: woosang0430/add-be:latest
    env_file:
      - ./.env
    ports:
      - 5000:5000
    networks:
      - add-network
    depends_on:
      - postgres
    restart: always
networks:
  add-network:
    external: true
