version: '3.5'

services:
  add-be:
    container_name: add-be
    image: woosang0430/add-be:latest
    env_file:
      - ./.env
    ports:
      - 5000:5000
    networks:
      - add-network
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - add-network
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
networks:
  add-network:
    driver: bridge
