name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Dockerhub
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_HUB_USERNAME/add-be:$(date +%s)

      - name: push to docker hub repository
        run: docker push $DOCKER_HUB_USERNAME/add-be:$(date +%s)
